name: Enforce allowable branch names for PRs to main

on:
  pull_request:
    branches: [main]
  merge_group:
    types: [checks_requested]


jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check if source branch is allowed
        run: |
          ALLOWED_PREFIXES=("release/")
          BRANCH_NAME="${{ github.head_ref }}"
          MATCHED=false

          for prefix in "${ALLOWED_PREFIXES[@]}"; do
            if [[ "$BRANCH_NAME" == $prefix* ]]; then
              MATCHED=true
              break
            fi
          done

          if [ "$MATCHED" = false ]; then
            echo "Branch '$BRANCH_NAME' is not allowed to merge into main."
            exit 1
          fi
